package main

import (
	"fmt"
	"log"
	"math/rand"
	"os"
	"regexp"
	"time"
)

// Define words in different languages
var words = map[string][]string{
	"es": {
		"AGUILA", "AMOR", "AVENTURA", "AZUL", "BELLEZA", "BLANCO", "BOSQUE", "BRILLO",
		"CALMA", "CAMINO", "CANCION", "CIELO", "CLARO", "CORAZON", "CORAJE", "CREACION",
		"DESTINO", "DIAMANTE", "DULZURA", "ENERGIA", "ESPERANZA", "ESTRELLA", "ETERNO",
		"FELICIDAD", "FLOR", "FORTALEZA", "FRAGANCIA", "FUEGO", "FUERZA", "HARMONIA",
		"HONOR", "HUMILDAD", "ILUSION", "INFINITO", "INTENSIDAD", "JOYA", "JUVENTUD", "LUZ",
		"LIBERTAD", "MISTERIO", "MUJER", "NATURALEZA", "NOCHE", "NOVEDAD", "OCASO", "ORGULLO",
		"PASION", "PAZ", "PODER", "PRIMAVERA", "PUREZA", "QUIMERA", "RADIANCIA", "REALIDAD",
		"REFLEJO", "RELAMPAGO", "RENACER", "RESPLANDOR", "RIQUEZA", "SABIDURIA", "SERENIDAD",
		"SINFONIA", "SONIDO", "SUENO", "TERNURA", "TIERRA", "TRUENO", "VALENTIA", "VERDAD",
		"VIENTO", "VIDA", "VOLUNTAD", "CANTO", "CAMPO", "CORONA", "CENTELLA", "CENTRO",
		"ESPIRITU", "ALMA", "SOMBRA", "AURA", "PLENITUD", "LAGO", "MAR", "RIO", "OLAS", "ESTILO",
		"DESTREZA", "GRACIA", "COLOR", "HORIZONTE", "RAIZ", "RITMO", "ONDA", "ORIGEN", "MAGIA",
		"TIEMPO", "CAMBIO", "ESENCIA", "VICTORIA", "LENGUAJE", "MEMORIA", "PUENTE", "FOCO",
		"GESTO", "IMAGEN", "ARMONIA", "EVOLUCION", "AVANCE", "FANTASIA", "HUMANIDAD", "PUEBLO",
		"CIUDAD", "ESPACIO", "MUSICA", "MOVIMIENTO", "IDEAL", "SABOR", "BRISA", "VENTISCA",
		"RECUERDO", "FRAGILIDAD", "CONCIENCIA", "INOCENCIA", "VERANO", "OTONO", "INVIERNO",
		"AROMA", "OLOR", "SAZON", "ALEGRIA", "CONFIANZA", "INTUICION", "OBRA", "DESPERTAR",
		"VISION", "ESPERA", "AFECTO", "TRABAJO", "GENIO", "SOLIDARIDAD", "HISTORIA", "CORTEZA",
		"MARAVILLA", "CONQUISTA", "TRADICION", "LEYENDA", "SIMBOLO", "PASADO", "PRESENTE",
		"FUTURO", "LUCHA", "META", "INICIO", "PRINCIPIO", "ALIMENTO", "ABRAZO", "ENCUENTRO",
		"REFUGIO", "ABUNDANCIA", "PERDIDA", "RETO", "EMOCION", "EXPERIENCIA", "RAZON", "LABOR",
		"EQUILIBRIO", "DIFICULTAD", "CONSTANCIA", "AUSENCIA", "ALIVIO", "RETORNO", "PROPUESTA",
		"APOYO", "TESTIMONIO", "FIRMEZA", "VOCACION", "PROPOSITO", "DESAFIO", "ENTENDIMIENTO",
		"RESOLUCION", "PERSISTENCIA", "EXITO", "RECONOCIMIENTO", "ACTITUD", "COMUNION", "DINAMISMO",
		"PERFECCION", "ALIENTO", "HIELO", "LLUVIA", "NUBE", "ESTALLIDO", "CREPUSCULO", "AMANECER",
		"CLARIDAD", "NEBLINA", "ROCIO", "ORILLA", "ESTABILIDAD", "ORIGEN", "EXISTENCIA", "DIGNIDAD",
		"INTEGRIDAD", "SINCERIDAD", "LEALTAD", "FIDELIDAD", "COMPROMISO", "HONRADEZ", "DISCIPLINA",
		"RESPETO", "GENEROSIDAD", "BONDAD", "VALOR", "PRUDENCIA", "CURIOSIDAD", "DESCUBRIMIENTO",
		"EMPEÑO", "ESFUERZO", "AMBICION", "SUEÑO", "DESEO", "VIAJE", "DECISION", "LOGRO",
		"INTELIGENCIA", "ASTUCIA", "INNOVACION", "CREATIVIDAD", "LIDERAZGO", "INFLUENCIA",
		"IMAGINACION", "INVENTO", "DESARROLLO", "PROGRESO", "INSPIRACION", "MISTERIO", "CULTURA",
		"PATRIMONIO", "RELIGION", "CREENCIA", "MITO", "ESPIRITUALIDAD", "MORALIDAD", "TALENTO",
		"HABILIDAD", "CRECIMIENTO", "FORMACION", "EDUCACION", "AMISTAD", "COMPANIA", "SOCIEDAD",
		"COOPERACION", "HERMANDAD", "RECIPROCIDAD", "IGUALDAD", "PARTICIPACION", "INCLUSIVIDAD",
		"JUSTICIA", "DIVERSIDAD", "COLABORACION", "ACUERDO", "DIALOGO", "CONCILIACION",
		"RECONCILIACION", "UNIDAD", "INTERDEPENDENCIA", "PROXIMIDAD", "RED", "CONEXION",
		"INTERCAMBIO", "COMUNICACION", "RELACION", "VINCULO", "CONCIENCIA", "ALIANZA", "SINTONIA",
		"INTERACCION", "COHESION", "MUTUALIDAD", "EQUIPO", "CAMARADERIA", "INTEGRACION",
		"COMPROMISO", "UNION", "FUERZA", "SINERGIA", "COMPANERISMO", "ESCUCHA", "CIENCIA",
		"TECNOLOGIA", "ARTE", "LITERATURA", "HISTORIA", "FILOSOFIA", "MATEMATICA", "BIOLOGIA",
		"FISICA", "QUIMICA", "ASTRONOMIA", "GEOLOGIA", "ECOLOGIA", "PSICOLOGIA", "SOCIOLOGIA",
		"ANTROPOLOGIA", "MEDICINA", "AGRICULTURA", "INGENIERIA", "ARQUITECTURA", "ADMINISTRACION",
		"ECONOMIA", "POLITICA", "DERECHO", "CIUDADANIA", "BIENESTAR", "SALUD", "ALIMENTACION",
		"DEPORTE", "RECREACION", "CULTURA", "PAISAJE", "GEOGRAFIA", "TURISMO", "HOSPITALIDAD",
		"SEGURIDAD", "DEFENSA", "ORDEN", "JUSTICIA", "PROTECCION", "CONSERVACION", "PATRIMONIO",
		"LENGUAJE", "COMUNICACION", "EXPRESION", "INFORMACION", "TECNOLOGIA", "PROGRESO",
		"CIVILIZACION", "DESARROLLO", "CONOCIMIENTO", "EDUCACION", "SABIDURIA", "INNOVACION",
		"INVESTIGACION", "FORMACION", "ENTRETENIMIENTO", "HABILIDAD", "DESTREZA", "POTENCIAL",
		"CURIOSIDAD", "EXPERIENCIA", "IMAGINACION", "CREATIVIDAD", "INSPIRACION", "TALENTO",
		"VOCACION", "SUEÑO", "META", "ASPIRACION", "VISION", "REALIZACION", "LIDERAZGO",
		"INICIATIVA", "EXITO", "LOGRO", "AMBICION", "TRABAJO", "COLABORACION", "SOLIDARIDAD",
		"INCLUSIVIDAD", "RESPONSABILIDAD", "COMPROMISO", "COOPERACION", "PERSEVERANCIA", "FORTALEZA",
		"DISCIPLINA", "SINCERIDAD", "HONESTIDAD", "CONFIANZA", "FIDELIDAD", "RESPETO", "VALOR",
		"ENTUSIASMO", "ENERGIA", "HUMILDAD", "INTEGRIDAD", "LEALTAD", "ALTRUISMO", "BONDAD",
		"CORTESIA", "GENEROSIDAD", "SOLIDARIDAD", "CIVISMO", "HONOR", "VALENTIA", "HEROISMO",
		"AGUILA", "ALCE", "ARANA", "AVESTRUZ", "BALLENA", "BISONTE", "BUHO", "BURRO",
		"CABALLO", "CABRA", "CACATUA", "CAMALEON", "CANGREJO", "CANGURO", "CARACOL", "CASTOR",
		"CEBRA", "CERDO", "CHACAL", "CHIMPANCE", "CIGUEÑA", "CIERVO", "COCODRILO", "COLIBRI",
		"CONDOR", "CONEJO", "COTORRA", "CUERVO", "DROMEDARIO", "ELEFANTE", "ERMELLON", "ESCARABAJO",
		"ESCUERZO", "FALCON", "FOCA", "GACELA", "GALLO", "GATO", "GAVIOTA", "GOLONDRINA",
		"GORILA", "GUACAMAYA", "HALCON", "HAMSTER", "HIPOPOTAMO", "HORMIGA", "HURON", "IGUANA",
		"JABALI", "JAGUAR", "JIRAFA", "KOALA", "LANGOSTA", "LEON", "LEOPARDO", "LIBELULA",
		"LLAMA", "LOBO", "LORO", "MANDRIL", "MARMOTA", "MEJILLON", "MOFETA", "MONO",
		"MURCIELAGO", "NUTRIA", "OCELOTE", "ORNITORRINCO", "OSO", "OSTRA", "OVEJA", "PANDA",
		"PANTERA", "PAVO", "PAVOREAL", "PELICANO", "PERDIZ", "PERRO", "PINGUINO", "PIRANA",
		"POLLO", "PUMA", "RANA", "RATON", "RENACUAJO", "RINOCERONTE", "SALMON", "SALTAMONTES",
		"SARDINA", "SERPIENTE", "TEJON", "TIBURON", "TIGRE", "TOPO", "TORO", "TORTUGA",
		"TRUCHA", "TUCAN", "VENADO", "VICUNA", "VIBORA", "ZORRO", "ZURDO",
		"BABUINO", "BONITO", "BUFALO", "CABALLO", "CANGREJO", "CARACOL", "CODORNIZ",
		"DROMEDARIO", "ESMERALDA", "FALCON", "GORRION", "HORMIGA", "IGUANA", "JABALI",
		"JACANA", "KOALA", "LIEBRE", "LOBOMARINO", "MAPACHE", "MULA", "OSOPOLAR", "PANGOLIN",
		"PALOMA", "PINGUINO", "PULPO", "QUETZAL", "QUOKKA", "RATON", "SALAMANDRA", "SARDINA",
		"TARANTULA", "TORTUGAMARINA", "URUBU", "VICUNA", "WAPITI", "XENOPE", "YACARE", "YEGUA",
		"ZANATE", "ZEBRA", "ZORRILLO", "ZORRO", "ZURDO",
		"BUENOSAIRES", "CORDOBA", "ROSARIO", "MENDOZA", "LAHABANA", "SANTIAGO", "VALPARAISO",
		"BOGOTA", "MEDELLIN", "CALI", "LIMA", "AREQUIPA", "CUSCO", "QUITO", "GUAYAQUIL",
		"CARACAS", "MARACAIBO", "BARQUISIMETO", "LAALTAGRACIA", "SANJOSE", "HEREDIA", "CARTAGO",
		"PANAMA", "COLON", "CHITRE", "SANJUAN", "PONCE", "MAYAGUEZ", "RIONEGRO", "MONTEVIDEO",
		"PUNTADELESTE", "SALTO", "ASUNCION", "CIUDADELESTE", "ENCARNACION", "RIODEJANEIRO",
		"SAOPAULO", "BRASILIA", "SALVADOR", "FORTALEZA", "LAPAZ", "SANTACRUZ", "COCHABAMBA",
		"SUCRE", "CIUDADDEMEXICO", "GUADALAJARA", "MONTERREY", "MERIDA", "TIJUANA", "PUEBLA",
		"LEON", "QUERETARO", "CANCUN", "SANTIAGODELSALVADOR", "SANMIGUEL", "MEXICALI",
		"SANPEDRO", "TEGUCIGALPA", "SANPEDROSULA", "CHOLUTECA", "MANAGUA", "LEON", "GRANADA",
		"SANJOSEDEGUANIPA", "CATALINA", "ORURO", "ANTOFAGASTA", "LAFLORIDA", "SANBORJA",
		"VIEDMA", "SANLUIS", "CORRIENTES", "FORMOSA", "RESISTENCIA", "SANJUAN", "POSADAS",
		"VILLAHERMOSA", "CULIACAN", "MAZATLAN", "CIUDADOBREGON", "AGUASCALIENTES", "MATAMOROS",
		"CARTAGENA", "BARRANQUILLA", "IBAGUE", "CUENCA", "PORTOVIEJO", "ESMERALDAS", "MACHALA",
		"SANFERNANDO", "TACNA", "TRUJILLO", "CHICLAYO", "JULIACA", "PUCALLPA", "CALLAO",
		"PACHUCA", "TLAXCALA", "CIUDADVICTORIA", "VILLADELROSARIO", "MAICAO", "VALLEDUPAR",
		"MACHUPICCHU", "HUARAZ", "SANMARTIN", "COJEDES", "MONAGAS", "GUANARE", "CARONI",
		"CAGUAS", "GUAYNABO", "BAYAMON", "CABOHAITIANO", "CAPHAITIEN", "PORTAUPRINCE",
		"SANTODOMINGO", "HIGUEY", "SANTIAGO", "PUERTOPRINCIPE", "MANZANILLO", "VARADERO",
		"CIENFUEGOS", "CAMAGUEY", "BAYAMO", "HOLGUIN", "BARACOA", "SANTIAGODECUBA", "SANCRISTOBAL",
		"SANCARLOS", "MARACAY", "PUERTOLAUNION", "LIBERTAD", "JUIGALPA", "SANJUANDELURUGUAY",
		"MARDELPLATA", "NEUQUEN", "RIOGRANDE", "USHUAIA", "ANCUD", "CASTRO", "PUNTAARENAS",
		"PUERTONATALES", "BARILOCHE", "PUCON", "VINADELMAR", "VALDIVIA", "TEMUCO", "PUERTOMONTT",
		"COPIAPO", "OSORNO", "VALLEGRANDE", "RIBERALTA", "MONTERO", "QUITO", "AMBATO",
		"SANCRISTOBAL", "MACHALILLA", "MALECON", "GUADALAJARA", "MORELIA", "CHIHUAHUA",
		"CUIDADJUAREZ", "CANCUN", "TOLUCA", "CHETUMAL", "IGUALA", "ACAPULCO", "TAMPICO",
		"VERACRUZ", "COATZACOALCOS", "ORURO", "PUNO", "TUMBES", "CHICLAYO", "CHIMBOTE",
		"TULCAN", "BILBAO", "GETXO", "SANTURTZI", "ERANDIO", "MADRID", "BARCELONA", "VALENCIA",
		"MALAGA", "SEVILLA", "BILBAO", "ZARAGOZA", "CORDOBA", "SANTIAGO", "MALAGA", "VALLEDUPAR",
		"BARRANQUILLA", "IBAGUE", "MANIZALES", "ARMENIA", "NEIVA", "POPAYAN", "SANJOSE",
	},
	"en": {
		"EAGLE", "LOVE", "ADVENTURE", "BLUE", "BEAUTY", "WHITE", "FOREST", "SHINE",
		"NEWYORK", "MIAMI", "CHICAGO", "DALLAS", "BOSTON", "SEATTLE", "AUSTIN", "OCEAN",
		"STAR", "LIGHT", "MOUNTAIN", "RIVER", "LAKE", "FIRE", "MOON", "SUN", "SKY",
		"STORM", "THUNDER", "RAIN", "SNOW", "SUNRISE", "SUNSET", "DREAM", "HEART",
		"SPIRIT", "FREEDOM", "PEACE", "HARMONY", "ENERGY", "POWER", "WILD", "SOUL",
		"ROCK", "ISLAND", "WIND", "SAND", "DESERT", "VALLEY", "CLIFF", "WAVE", "TIDE",
		"STREAM", "MEADOW", "FOREST", "HORIZON", "JOURNEY", "PATH", "ROAD", "TRACK",
		"FOOTPRINT", "TREE", "LEAF", "FLOWER", "PETAL", "BLOSSOM", "BIRD", "ANIMAL",
		"BUTTERFLY", "WOLF", "FOX", "LION", "TIGER", "BEAR", "DEER", "HORSE", "DOG",
		"CAT", "FISH", "EAGLE", "DOLPHIN", "SHARK", "WHALE", "TURTLE", "FALCON",
		"HAWK", "OWL", "DRAGON", "PHOENIX", "MYSTERY", "MAGIC", "WONDER", "GRACE",
		"GLORY", "HONOR", "COURAGE", "VICTORY", "LEGEND", "MYTH", "DESTINY", "FATE",
		"TIME", "ETERNITY", "FOREVER", "MEMORY", "MOMENT", "MIRACLE", "UNIVERSE",
		"GALAXY", "PLANET", "EARTH", "WATER", "AIR", "NATURE", "BEYOND", "INFINITY",
		"UNITY", "TOGETHER", "FAMILY", "FRIENDSHIP", "LOVE", "KINDNESS", "HOPE",
		"LIGHT", "SHADOW", "DARKNESS", "SECRET", "TRUTH", "MIND", "THOUGHT", "DREAM",
		"VISION", "WISDOM", "KNOWLEDGE", "INSIGHT", "DISCOVERY", "MYSTERY", "MIRACLE",
		"HORIZON", "VOYAGE", "ODYSSEY", "TRAVEL", "EXPLORER", "PIONEER", "NAVIGATOR",
		"JOURNEY", "ADVENTURER", "WANDERER", "SEEKER", "QUEST", "EXPERIENCE", "SAGA",
		"EPIC", "MEMOIR", "CHRONICLE", "HISTORY", "LEGACY", "HERITAGE", "ORIGIN",
		"GENESIS", "CREATION", "BEGINNING", "SOURCE", "ROOT", "ANCESTOR", "NATIVE",
		"EARTH", "SOIL", "STONE", "ROCK", "MOUNTAIN", "HILL", "PLATEAU", "PEAK",
		"SUMMIT", "RIDGE", "VALLEY", "CANYON", "GROVE", "ORCHARD", "WOODLAND", "FIELD",
		"PASTURE", "MEADOW", "SWAMP", "MARSH", "RIVER", "STREAM", "BROOK", "CREEK",
		"LAKE", "POND", "SEA", "OCEAN", "BAY", "COAST", "SHORE", "BEACH", "DUNE",
		"WAVE", "TIDE", "CURRENT", "REEF", "CORAL", "ABYSS", "DEEP", "CAVE", "CAVERN",
		"GLACIER", "ICEBERG", "FOG", "MIST", "CLOUD", "RAIN", "STORM", "THUNDER",
		"LIGHTNING", "SNOW", "FROST", "ICE", "CRYSTAL", "DIAMOND", "JEWEL", "TREASURE",
		"WEALTH", "FORTUNE", "GOLD", "SILVER", "BRONZE", "COPPER", "IRON", "STEEL",
		"SWORD", "SHIELD", "ARMOR", "BATTLE", "WAR", "PEACE", "TRUCE", "ALLIANCE",
		"VICTORY", "TRIUMPH", "GLORY", "FAME", "LEGEND", "HERO", "CHAMPION", "LEADER",
		"KING", "QUEEN", "PRINCE", "PRINCESS", "EMPEROR", "MONARCH", "ROYAL", "KNIGHT",
		"SAGE", "WIZARD", "MAGE", "SHAMAN", "HEALER", "PROPHET", "MYSTIC", "ORACLE",
		"SCHOLAR", "PHILOSOPHER", "THINKER", "POET", "ARTIST", "SCULPTOR", "PAINTER",
		"MUSICIAN", "DANCER", "ACTOR", "WRITER", "AUTHOR", "CREATOR", "BUILDER",
		"INVENTOR", "ENGINEER", "SCIENTIST", "EXPLORER", "PIONEER", "TRAVELER",
		"ADVENTURER", "SEEKER", "WANDERER", "NOMAD", "MIGRANT", "VOYAGER", "CAPTAIN",
		"SAILOR", "PILOT", "NAVIGATOR", "PATHFINDER", "RANGER", "SCOUT", "GUARDIAN",
		"DEFENDER", "WATCHER", "PROTECTOR", "KEEPER", "GUIDE", "MENTOR", "TEACHER",
		"STUDENT", "APPRENTICE", "LEARNER", "FOLLOWER", "DISCIPLE", "BELIEVER",
		"CHALLENGER", "COMPETITOR", "OPPONENT", "RIVAL", "ALLY", "FRIEND", "COMPANION",
		"PARTNER", "TEAMMATE", "ASSOCIATE", "COLLEAGUE", "PEER", "FELLOW", "ACQUAINTANCE",
		"NEIGHBOR", "STRANGER", "VISITOR", "GUEST", "HOST", "RESIDENT", "INHABITANT",
		"CITIZEN", "VILLAGER", "NOMAD", "SETTLER", "PIONEER", "PATHFINDER",
		"LION", "TIGER", "ELEPHANT", "GIRAFFE", "ZEBRA", "LEOPARD", "CHEETAH", "RHINOCEROS",
		"HIPPOPOTAMUS", "CROCODILE", "ALLIGATOR", "GORILLA", "CHIMPANZEE", "MONKEY",
		"ORANGUTAN", "PANDA", "KOALA", "KANGAROO", "WALLABY", "WOMBAT", "RACCOON",
		"SLOTH", "ANTEATER", "ARMADILLO", "BAT", "FOX", "WOLF", "COYOTE", "HYENA",
		"JACKAL", "BEAR", "POLARBEAR", "GRIZZLY", "BROWNBEAR", "BLACKBEAR", "PUMA",
		"JAGUAR", "LYNX", "BOBCAT", "CARACAL", "SERVAL", "OTTER", "BEAVER", "BADGER",
		"HEDGEHOG", "MOLE", "SHREW", "RAT", "MOUSE", "HAMSTER", "GERBIL", "GUINEAPIG",
		"SQUIRREL", "CHIPMUNK", "PRAIRIEDOG", "MARMOT", "CAPYBARA", "DEGU", "CHINCHILLA",
		"FERRET", "OPOSSUM", "BANDICOOT", "NUMBAT", "QUOKKA", "DINGO", "TASMANIANDEVIL",
		"MOLE", "SKUNK", "WEASEL", "STOAT", "MINK", "ERMINE", "PORCUPINE", "HARE",
		"RABBIT", "PINEAPPLEFISH", "SEAHORSE", "PUFFERFISH", "BLOWFISH", "ANGELFISH",
		"CLOWNFISH", "BUTTERFLYFISH", "BASS", "TROUT", "SALMON", "SHARK", "WHALE",
		"DOLPHIN", "PORPOISE", "OCTOPUS", "SQUID", "CUTTLEFISH", "LOBSTER", "CRAB",
		"SHRIMP", "PRAWN", "JELLYFISH", "SEAURCHIN", "STARFISH", "ANEMONE", "CORAL",
		"SEASNAKE", "SEACUCUMBER", "WORM", "LEECH", "SPONGE", "PLANKTON", "MANTA",
		"RAY", "EEL", "TUNA", "SWORD", "ANCHOVY", "SARDINE", "HERRING", "PIRANHA",
		"BARRACUDA", "STINGRAY", "FLYINGFISH", "CATFISH", "CARP", "KOI", "PERCH",
		"PEACOCK", "ROBIN", "SPARROW", "PARROT", "PARAKEET", "MACAW", "BUDGIE",
		"COCKATOO", "TOUCAN", "FLAMINGO", "SWAN", "GOOSE", "DUCK", "OWL", "EAGLE",
		"FALCON", "HAWK", "BUZZARD", "OSPREY", "KIWI", "EMU", "OSTRICH", "PENGUIN",
		"ALBATROSS", "CONDOR", "VULTURE", "HUMMINGBIRD", "WOODPECKER", "CROW", "RAVEN",
		"BLACKBIRD", "STARLING", "THRUSH", "FINCH", "BUNTING", "WARBLER", "CANARY",
		"NIGHTINGALE", "HERON", "CRANE", "STORK", "IBIS", "SPOONBILL", "PELICAN",
		"MOCKINGBIRD", "BLUEJAY", "CARDINAL", "KINGFISHER", "KITE", "SEAGULL",
		"PUFFIN", "PLOVER", "SANDPIPER", "WADER", "GROUSE", "PTARMIGAN", "QUAIL",
		"PARTRIDGE", "PHEASANT", "TURKEY", "CHICKEN", "PIGEON", "DOVE", "COCK",
		"SWIFT", "SWALLOW", "BEE-EATER", "MARTIN", "BITTERN", "RAIL", "COOT", "GALLINULE",
		"MAGPIE", "JAY", "ROOK", "NUTCRACKER", "CHUCKWILL'SWIDOW", "BOWERBIRD",
		"LYREBIRD", "HARRIER", "SEAHAWK", "KINGPENGUIN", "LIONFISH", "STINGFISH",
		"GORILLA", "CHIMP", "ORANGUTAN", "LEMUR", "BABOON", "MANDRILL", "VULTURE",
		"MONARCHBUTTERFLY", "SILKMOTH", "LEOPARD", "CHEETAH", "LIZARD", "GECKO",
		"IGUANA", "MONITORLIZARD", "CHAMELEON", "DRAGONFLY", "DAMSELFLY", "CRICKET",
		"GRASSHOPPER", "LOCUST", "BEE", "WASP", "HORNET", "ANT", "TERMIT", "COCKROACH",
		"LADYBUG", "FIREFLY", "MOSQUITO", "MIDGE", "GNAT", "BUTTERFLY", "MOTH",
		"SILVERFISH", "DRAGON", "DRAGON", "UNICORN", "PEGASUS", "GRIFFIN", "PHOENIX",
		"WYVERN", "KRAKEN", "HYDRA", "BASILISK", "MERMAID", "CENTAUR", "SIREN",
		"TURTLE", "TOAD", "FROG", "SALAMANDER", "NEWT", "CAECILIAN", "SPIDER",
		"TARANTULA", "SCORPION", "CENTIPEDE", "MILLIPEDE", "EARTHWORM", "NIGHTCRAWLER",
		"HOOKWORM", "TAPEWORM", "ROUNDWORM", "FLATWORM", "LEECH", "PLANARIAN",
		"SNAKE", "COBRA", "VIPER", "PYTHON", "BOA", "ANACONDA", "RATTLESNAKE",
		"CORALSNAKE", "MAMBA", "COTTONMOUTH", "COPPERHEAD", "BOBCAT", "COUGAR",
		"WOLF", "COYOTE", "LYNX", "CARIBOU", "MOOSE", "ELK", "DEER", "ANTLER",
		"BISON", "BUFFALO", "GAZELLE", "IMPALA", "SPRINGBOK", "KUDU", "GIRAFFE",
		"CAMEL", "DROMEDARY", "LLAMA", "ALPACA", "VICUNA", "OKAPI", "RHINO",
		"ELEPHANT", "MAMMOTH", "DODO", "TASMANIANTIGER", "NEANDERTHAL", "SABERTOOTH",
		"MEGALODON", "DIMETRODON", "IGUANODON", "DINOSAUR", "BRONTOSAURUS", "T-REX",
		"TRICERATOPS", "PTERODACTYL", "VELOCIRAPTOR", "PLESIOSAUR", "STEGOSAURUS",
		"NEWYORK", "LOSANGELES", "CHICAGO", "HOUSTON", "PHOENIX", "PHILADELPHIA",
		"SANANTONIO", "SANDIEGO", "DALLAS", "SANDON", "MIAMI", "ATLANTA", "BOSTON",
		"SANFRANCISCO", "WASHINGTON", "SEATTLE", "DENVER", "LASVEGAS", "AUSTIN",
		"NASHVILLE", "DETROIT", "PORTLAND", "MEMPHIS", "INDIANAPOLIS", "CHARLOTTE",
		"ORLANDO", "SALTLAKECITY", "LOUISVILLE", "CLEVELAND", "KANSASCITY", "COLUMBUS",
		"JACKSONVILLE", "MILWAUKEE", "PROVIDENCE", "NEWORLEANS", "OKLAHOMACITY",
		"TULSA", "ALBUQUERQUE", "FRESNO", "SACRAMENTO", "ELPASO", "MESA", "OMAHA",
		"MINNEAPOLIS", "WICHITA", "BAKERSFIELD", "ARLINGTON", "TAMPA", "AURORA",
		"SANTAANA", "RIVERSIDE", "CORPUSCHRISTI", "STLOUIS", "PITTSBURGH", "CINCINNATI",
		"ANCHORAGE", "HONOLULU", "RALEIGH", "CHANDLER", "MADISON", "SCOTTSDALE",
		"RENO", "BOISE", "RICHMOND", "BATONROUGE", "HUNTSVILLE", "DESMOINES", "LAREDO",
		"CHESAPEAKE", "GARLAND", "LUBBOCK", "TUCSON", "FORTWORTH", "HENDERSON",
		"FORTLAUDERDALE", "STPAUL", "LINCOLN", "SPOKANE", "GRANDRAPIDS", "NEWARK",
		"JERSEYCITY", "BUFFALO", "ROCHESTER", "YONKERS", "WORCESTER", "SPRINGFIELD",
		"SYRACUSE", "BRIDGEPORT", "SIOUXFALLS", "FORTWAYNE", "PEORIA", "DAVENPORT",
		"SHREVEPORT", "EVANSVILLE", "KNOXVILLE", "FAYETTEVILLE", "CHARLESTON", "SAVANNAH",
		"LANCASTER", "GREENSBORO", "NORTHCHARLESTON", "HARTFORD", "ALEXANDRIA",
		"MCALLEN", "KILLEEN", "PLANO", "MOBILE", "BROWNSVILLE", "TALLAHASSEE",
		"HOLLYWOOD", "PASADENA", "HAMPTON", "ROCKFORD", "NAPERVILLE", "JOLIET",
		"CARY", "COLUMBIA", "TOPEKA", "VIRGINIABEACH", "ABERDEEN", "OXFORD",
		"CAMBRIDGE", "DERBY", "BIRMINGHAM", "LIVERPOOL", "MANCHESTER", "EDINBURGH",
		"GLASGOW", "BRISTOL", "NOTTINGHAM", "CARDIFF", "LEEDS", "SHEFFIELD",
		"BELFAST", "DUNDEE", "NEWCASTLE", "PORTSMOUTH", "SOUTHAMPTON", "PLYMOUTH",
		"STOKE", "WOLVERHAMPTON", "BRIGHTON", "LEICESTER", "KINGSTON", "NORWICH",
		"HULL", "YORK", "BATH", "COVENTRY", "SWANSEA", "READING", "WINCHESTER",
		"OXFORD", "CAMBRIDGE", "TORONTO", "MONTREAL", "VANCOUVER", "CALGARY",
		"OTTAWA", "EDMONTON", "QUEBEC", "WINNIPEG", "HAMILTON", "KITCHENER",
		"LONDON", "VICTORIA", "HALIFAX", "SASKATOON", "STJOHNS", "THUNDERBAY",
		"SURREY", "REGINA", "KINGSTON", "MISSISSAUGA", "NIAGARAFALLS", "OSHAWA",
		"GATINEAU", "BARRIE", "RICHMOND", "SAINTJOHN", "SUDBURY", "BRAMPTON",
		"BURNABY", "COQUITLAM", "LETHBRIDGE", "MONCTON", "REDDEER", "ABBOTSFORD",
		"SAGUENAY", "SAINTJEROME", "VARENNES", "PETERBOROUGH", "BROSSARD", "JOLIETTE",
		"RIMOUSKI", "SAINTGEORGES", "YARMOUTH", "SAINTEHYACINTHE", "MASCOUCHE",
		"LAVAL", "LANGLEY", "MAPLE", "KAMLOOPS", "MEDICINEHAT", "GRANBY",
		"SHERBROOKE", "VALDOR", "SHAWINIGAN", "SAINTSAUVEUR", "VICTORIAVILLE",
		"RICHMONDHILL", "NANAIMO", "COWANSVILLE", "THREEHILLS", "WEYMOUTH", "SACKVILLE",
		"CARBONEAR", "CHARLOTTETOWN", "FREDERICTON", "SAINTJOHN", "LIVERPOOL",
		"LUNENBURG", "SUMMERSIDE", "PORTHAWKESBURY", "GRANDFALLS", "WELLAND",
		"HUNTSVILLE", "PARRY", "BRACEBRIDGE", "BROOKSVILLE", "VERNON", "COURTENAY",
		"SQUAMISH", "WHISTLER", "TERRACE", "KITIMAT", "PRINCERUPERT", "QUESNEL",
		"SALMONARM", "POWELLRIVER", "PRINCEGEORGE", "SAULTSTEMARIE", "THUNDERBAY",
		"TEMAGAMI", "COCHRANE", "MOOSONEE", "CHURCHILL", "FLINFLON", "THOMPSON",
		"GILLAM", "BEAUMONT", "FORTMCMURRAY", "GRANDEPRAIRIE", "PINCHERCREEK",
		"CALGARY", "BANFF", "JASPER", "CANMORE", "YELLOWKNIFE", "INUVIK", "IQALUIT",
		"RANKININLET", "WHITEHORSE", "DAWSONCITY", "WATSONLAKE", "CARMACKS", "HAYRIVER",
		"FORTSMITH", "BEAVERLODGE", "MAUN", "LOBATSE", "GABORONE", "KASANE",
		"FRANCISTOWN", "TSABONG", "SELEBI-PHIKWE", "TULI-BLOCK", "RAMOTSWA",
		"TUTUME", "KALABO", "NAMYUNGA", "KOKOMA", "NAIROBI", "DODOMA", "MOROGORO",
		"MBEYA", "ARUSHA", "DAR", "MWANZA", "KAMPALA", "LUANDA", "LIBREVILLE",
		"MBABANE", "LOBATSE", "LUWERO", "LUSAKA", "MAUN", "KINSHASA", "BRAZZAVILLE",
		"GABORONE", "MASERU", "MAPUTO", "MOGADISHU", "DJIBOUTI", "ASMARA", "MARRAKESH",
		"CASABLANCA", "AGADIR", "RABAT", "OUARZAZATE", "MOMBASA", "PORTLOUIS",
		"RODRIGUES", "CASTRIES", "SOUFRIERE", "VIEUXFORT", "BEQUILA", "MUSTIQUE",
		"ARIMA", "PORTSPAIN", "TUNAPUNA", "MALABAR", "MAYARO", "SANFERNANDO",
	},
	"pt": {
		"AMOR", "ALEGRIA", "PAZ", "FORCA", "LUZ", "SOL", "LUAR", "ESTRELA", "MAR",
		"RIO", "FLORESTA", "MONTANHA", "VALE", "SERTAO", "CACHOEIRA", "LAGO", "PRAIA",
		"VENTO", "TEMPO", "NATUREZA", "TERRA", "FOGO", "AGUA", "CEU", "NUBLADO",
		"CHUVA", "NEVE", "TROVAO", "RELAMPEJO", "ONDA", "FLOR", "ARVORE", "FOLHA",
		"FRUTO", "VIDA", "DESTINO", "HARMONIA", "ESPERANCA", "VERDADE", "MISTERIO",
		"SONHO", "MAGIA", "ENCANTO", "SILENCIO", "CALMARIA", "ECO", "VOZ", "CORAGEM",
		"DESAFIO", "VITORIA", "GLORIA", "HONRA", "LEGADO", "SABEDORIA", "CONHECIMENTO",
		"ARTE", "PINTURA", "MUSICA", "DANCA", "POESIA", "TEATRO", "CULTURA", "CANTO",
		"RISADA", "HUMOR", "AMIZADE", "COMPANHIA", "FAMILIA", "AMIZADE", "RESPEITO",
		"GUERREIRO", "HERANCA", "HISTORIA", "ORIGEM", "INICIO", "DESCOBERTA", "SAUDADE",
		"VERDE", "AZUL", "BRANCO", "PRETO", "CINZA", "DOURADO", "PRATA", "BRILHO",
		"SOMBRA", "FOGO", "GELO", "ESPIRITO", "FORCA", "MISTERIO", "ENERGIA", "ALMA",
		"ESPACO", "PLANETA", "GALAXIA", "UNIVERSO", "ESTRELA", "MAR", "ROCHA", "AREIA",
		"DUNA", "DESERTO", "SELVA", "RIBEIRA", "HORIZONTE", "AVENTURA", "VIAGEM",
		"DESCOBERTA", "CAVERNA", "GRUTA", "PEDRA", "VIDA", "DESAFIO", "FUTURO",
		"PRESENTE", "PASSADO", "MOMENTO", "MEMORIA", "IMAGINACAO", "REALIDADE", "SONHO",
		"INSPIRACAO", "ILUSAO", "INOVACAO", "PAIXAO", "CARINHO", "SAUDE", "FORTALEZA",
		"VIAGEM", "CAMINHO", "JORNADA", "TRILHA", "DESTINO", "FUSO", "DISTANCIA",
		"TRAJETORIA", "RUMO", "EXPLORADOR", "NAUFRAGIO", "TURBULENCIA", "RAIO", "FOGO",
		"ALVORECER", "ANOITECER", "OCASO", "MEIO-DIA", "NOITE", "CREPUSCULO", "AMANHECER",
		"PORTO", "RUMO", "ALMA", "SAUDADE", "MEMORIA", "SILENCIO", "PRESENCA", "SABEDORIA",
		"SAGRADO", "PROFETA", "MESTRE", "DOUTOR", "FILOSOFIA", "CONSELHO", "JUSTICA",
		"LEALDADE", "PRUDENCIA", "COMPREENSAO", "ESTUDIOSO", "CIENCIA", "INOVACAO",
		"SERVICO", "TRABALHO", "ESPERANCA", "JUSTICA", "REMEDIO", "VIDA", "CURA",
		"NATUREZA", "AGUA", "ROCHA", "FERRO", "OURO", "DIAMANTE", "SAFIRA", "ESMERALDA",
		"CRISTAL", "PEDRA", "TESOURO", "MONTE", "LAGO", "VALE", "PICO", "ENCOSTA",
		"SERPENTE", "DRAGAO", "CARPA", "LOBO", "GATO", "CACHORRO", "PASSARO", "COELHO",
		"TARTARUGA", "PEIXE", "GOLFINHO", "SEREIA", "TIGRE", "LEAO", "URSO", "AGUIA",
		"RAPOSA", "PANTERA", "POLVO", "ESTRELA-DO-MAR", "CORUJA", "GAIVOTA", "VAGA-LUME",
		"BESOURO", "ABELHA", "FORMIGA", "ESCORPIAO", "BORBOLETA", "FENIX", "UNICORNIO",
		"GRIFO", "HIPOGRIFO", "CENTAURO", "ESPERANCA", "ACAO", "FE", "EQUILIBRIO",
		"INTUICAO", "FORTUNA", "LIBERDADE", "COMPANHEIRISMO", "FORCA", "TENACIDADE",
		"PERSISTENCIA", "VONTADE", "FOCO", "DESTINO", "ESCOLHA", "SABEDORIA", "PERDAO",
		"SOLIDAO", "ABUNDANCIA", "FELICIDADE", "TRANQUILIDADE", "SERENIDADE", "RESILIENCIA",
		"PERSEVERANCA", "ALEGRIA", "APRENDIZADO", "EMPATIA", "DESAPEGO", "ALMA", "VIBE",
		"SERENIDADE", "TRANQUILIDADE", "SERENO", "PAIXAO", "IMPULSO", "IMPETO", "HEROISMO",
		"FICCAO", "HISTORIA", "MITO", "LENDA", "FAZENDA", "CONTO", "IMAGINACAO", "MENTE",
		"EMOCAO", "INSTINTO", "RAZAO", "MORAL", "ETICA", "INTEGRIDADE", "CARATER",
		"VIRTUDE", "BONDADE", "CARIDADE", "SINCERIDADE", "HUMILDADE", "DEDICACAO",
		"PACIENCIA", "AMABILIDADE", "DISCIPLINA", "FELICIDADE", "HONESTIDADE", "BENEVOLECIA",
		"INTELIGENCIA", "CRIATIVIDADE", "INVENTIVIDADE", "AGILIDADE", "ASTUCIA", "ELOQUENCIA",
		"INDEPENDENCIA", "ALEGRIA", "RISADA", "LIBERDADE", "AUTOCONHECIMENTO", "VERDADE",
		"DESCANSO", "ALEGORIA", "VIRTUDE", "IDEAL", "ESPERANCA", "MIRAGEM", "SONHO",
		"LEALDADE", "IDEALISMO", "TRADICAO", "MISTICISMO", "ESPIRITUALIDADE", "FIDELIDADE",
		"FELICIDADE", "CALMA", "TRANQUILIDADE", "SONO", "INSPIRACAO", "APRECIACAO",
		"ADMIRACAO", "CONFIANCA", "COMPAIXAO", "LIBERDADE", "PAZ", "SERENIDADE",
		"VIGOR", "VIBRACAO", "ALEGRIA", "SUCESSO", "SORTE", "ALEGRIA", "LIDERANCA",
		"EXPERIENCA", "APRECIACAO", "RECONHECIMENTO", "GRATIDAO", "ADMIRACAO",
		"INFLUENCIA", "PODER", "FORCA", "CONFIANCA", "FE", "CONHECIMENTO", "INTELIGENCIA",
		"INSPIRACAO", "REALIZACAO", "SONHO", "INTENCAO", "EMPATIA", "SIMPLICIDADE",
		"APOIO", "PACIENCIA", "VIRTUDE", "DEDICACAO", "GENEROSIDADE", "CUIDADO",
		"FIRMEZA", "COERENCIA", "VONTADE", "ACAO", "DISPOSICAO", "FORCA", "RESPEITO",
		"INICIATIVA", "VISSAO", "HONRA", "PROTECAO", "AMOR", "FAMILIA", "LEALDADE",
		"ENTUSIASMO", "ORGANIZACAO", "LEVEZA", "PAIXAO", "CORAGEM", "TENACIDADE",
		"TRABALHO", "PERSEVERANCA", "RESILIENCIA",
		"CACHORRO", "GATO", "LEAO", "TIGRE", "ELEFANTE", "GIRAFA", "ZEBRA", "RINOCERONTE",
		"HIPOPOTAMO", "CROCODILO", "JACARE", "GORILA", "CHIMPANZE", "MACACO", "ORANGOTANGO",
		"PANDA", "KOALA", "CANGURU", "WALLABY", "VOMBATE", "GUAXINIM", "PREGUICA", "TAMANDUA",
		"TATU", "MORCEGO", "RAPOSA", "LOBO", "COIOTE", "HIENA", "CHACAL", "URSO", "URSOPOLAR",
		"URSOPARDO", "URSONEGRO", "PUMA", "JAGUAR", "LINCE", "LONTRA", "CASTOR", "TEXUGO",
		"OURICO", "TOUPEIRA", "MUSARANHO", "RATO", "CAMUNDONGO", "HAMSTER", "GERBIL", "PORQUINHODAINDIA",
		"ESQUILO", "ESQUILOVOADOR", "MARMOTA", "CAPIVARA", "DEGU", "CHINCHILA", "FURAO",
		"GAMBA", "ZORRO", "PAPAGAIO", "ARARA", "PERIQUITO", "CALOPSITA", "CANARIO", "SABIA",
		"BICHOPREGUICA", "TATUBOLA", "CABRA", "BOI", "VACA", "CARNEIRO", "OVELHA", "CAVALO",
		"JUMENTO", "BURRO", "GALO", "GALINHA", "PATO", "MARRECO", "GANSO", "PERU", "FAISAO",
		"PAVAO", "CODORNA", "GAIVOTA", "PELICANO", "FLAMINGO", "CORVO", "CORUJA", "FALCAO",
		"AGUIA", "ANDORINHA", "ROUXINOL", "PARDAL", "JOAODEBARRO", "CANARIO", "BICUDO",
		"URUBU", "GARCA", "CISNE", "ALBATROZ", "PICAPAU", "PINGUIM", "CARDINAL", "TUCANO",
		"POMBO", "CALANDRA", "SARACURA", "GAZELA", "VEADO", "CAMELO", "DROMEDARIO", "LHAMA",
		"ALPACA", "ANTILOPE", "BUFALO", "BIZAO", "ALCE", "RENO", "GAMO", "IMPALA", "CABRAMONTES",
		"BORBOLETA", "ABELHA", "VESPA", "JOANINHA", "CIGARRA", "MOSCA", "PERCEVEJO",
		"GRILO", "LOUVAADEUS", "ESCORPIAO", "CAVALOMARINHO", "POLVO", "LULA", "BALEIA",
		"GOLFINHO", "TUBARAO", "PEIXEPALHACO", "PEIXEBOI", "PEIXELUA", "ESPADARTE", "ANEMONA",
		"MARIMBONDO", "CARRAPATO", "PULGA", "LOBO", "LOBO-MARINHO", "TARTARUGA", "TARTARUGAMARINHA",
		"CARAMUJO", "ESCARGOT", "MINHOCA", "LEBRE", "COELHO", "BODE", "CARNEIRO", "PORCO",
		"PORCOESPINHO", "JAVALI", "GUEPARDO", "PANTERA", "LEOPARDO", "CHITA", "ONCA", "LEOPARDONEVADO",
		"SURIKATA", "FENEC", "GALODECAMPINA", "AVESTRUZ", "EMA", "BIZONTE", "BOIBRAVO",
		"CORCOVADO", "ANTA", "MANATI", "LONTRAMARINHA", "MORSA", "FOCA", "GATODOMATO",
		"ONCAPINTADA", "ONCAPARDA", "RINOCERONTEBRANCO", "RINOCERONTENEGRO", "COBRA",
		"SUCURI", "ANACONDA", "JARARACA", "CASCAVEL", "NAJA", "VIPERA", "MAMBANEGRA",
		"JIBOIA", "PITON", "CAMELEAO", "LAGARTO", "IGUANA", "GECO", "LAGARTIXA", "DRAGAODEKOMODO",
		"SALAMANDRA", "TRITAO", "SAPO", "RANA", "CARAMUJO", "POLVOGIGANTE", "CRACA",
		"SANGUESSUGA", "LAMPREIA", "PEIXEPADRE", "PEIXEBRUXA", "ENGUIA", "LAMPREIA",
		"TRUTA", "SALMAO", "BACALHAU", "LINGUADO", "SARDINHA", "ATUM", "PIROCA", "DOURADO",
		"PEIXEPAPAGAIO", "PEIXECIRURGIAO", "PEIXELEAO", "PEIXEESCORPIAO", "MANTARRAIA",
		"ARANHA", "TARANTULA", "LACRAIA", "CEMPES", "FORMIGA", "BESOURO", "MARIMBONDO",
		"ESCARAVELHO", "GRILO", "LOUVAADEUS", "BESOURORHINO", "ZANGAO", "ABELHAOPERARIA",
		"FORMIGASAUDITA", "PIOLHO", "LOUVAADEUSGIGANTE", "LOUVAADEUSORQUIDEA",
		"ESCORPIAONEGRO", "LOUVAADEUS", "FORMIGADEFOGO", "JOANINHAVERMELHA",
		"CORUJABURAQUEIRA", "FALCAOPELEGRINO", "CONDOR", "MUITOGRANDE", "EUMARA",
		"GALODASERRA", "PASSARODOPARAISO", "QUEROQUERO", "PAPAGAIOLOURO",
		"AGUIAPESCADORA", "CISNENEGRO", "CEGONHA", "PEIXEVOADOR", "PEIXEAGULHA",
		"CACHORRODOMATO", "TUCANOTOCO", "TUCANODEBICOVERDE", "TUCANODEBICOAMARELO",
		"ARARAAZUL", "ARARAVERMELHA", "ARARAVERDE", "CANDANGO", "TRIBO",
		"VEADOCAMPEIRO", "LOBISOMEM", "SAPOBUFO", "GALOPE", "COBRACIPO", "JACAREPIRANA",
		"SIRI", "CARANGUEJO", "LAGOSTA", "CAMARAO", "CAMARAOTIGRE", "CARANGUEJOERMITA",
		"VAGALUME", "PEIXESERRA", "TIGREDATASMANIA", "AVEIA", "CASTOR", "PEIXEESPADA",
		"FOCACINZA", "FOCAMARINHA", "FOCADAGROENLANDIA", "MORCEGOFANTASMA",
		"MACACOARANHA", "MACACOPREGO", "MACACOBUGIO", "MACACOMICO", "MACACOCABECADALGODAO",
		"LOBOCINZA", "LOBOBRANCO", "LOBOVERMELHO", "LOBOGRITADOR", "LOBOGUARA",
		"CACHORROVINAGRE", "COIOTE", "DONINHA", "FURAO", "FURAODOPIELO", "GATOMARACAJÁ",
		"ANACONDAVERDE", "TAMANDUABANDEIRA", "TAMANDUAMIRIM", "MICOLEAODOURADO",
		"MICOLEAOPRETO", "FOCAMONJE", "MACACOPREGO", "MICOESTRELA",

		"SAOPAULO", "RIODEJANEIRO", "BRASILIA", "SALVADOR", "FORTALEZA", "BELOHORIZONTE",
		"CURITIBA", "MANAUS", "RECIFE", "PORTOALEGRE", "GOIANIA", "GUARULHOS", "CAMPINAS",
		"SAOGONCALO", "SAOLUIS", "MACEIO", "DUQUEDECAXIAS", "NATAL", "TERESINA",
		"SAOJOSEDOSCAMPOS", "SAOBERNARDODOCAMPO", "NOVOIGUACU", "JOAOPESSOA", "SANTOS",
		"SOROCABA", "RIBEIRAOPRETO", "JUNDIAI", "UBERLANDIA", "CUIABA", "FEIRADESANTANA",
		"APARECIDEDOGOIANIA", "CAXIASDOSUL", "LONDRINA", "ARACAJU", "JOINVILLE",
		"JUAZEIRODONORTE", "ANAPOLIS", "NITEROI", "FLORIANOPOLIS", "VITORIA", "PETROLINA",
		"CAMPOGRANDE", "SANTAMARIA", "MACAPA", "VILAVELHA", "MAUA", "GUARAPUAVA",
		"MARINGA", "VOLTA REDONDA", "BLUMENAU", "BETIM", "SANTOS", "FRANCA", "IPATINGA",
		"BARUERI", "TAUBATE", "IMPERATRIZ", "RONDONOPOLIS", "PASSOFUNDO", "DIVINOPOLIS",
		"MACAE", "MOSSORO", "UBERABA", "RONDONOPOLIS", "PONTA GROSSA", "ILHEUS", "FERRAZDEVASCONCELOS",
		"GRAVATAI", "SAOGONCALO", "TABOAO", "CASTANHAL", "PALMAS", "BRUSQUE", "ARARUAMA",
		"OSASCO", "BARRETOS", "CABOFRIO", "UBERABA", "CAMACARI", "AMERICANA", "SOBRAL",
		"ALVORADA", "VIAMAO", "MARABA", "CANOAS", "GRAVATAI", "COTIA", "PIRACICABA",
		"JUIZDEFORA", "ANANINDEUA", "VARGINHA", "ITAQUAQUECETUBA", "ITABUNA", "LINHARES",
		"CONSELHEIROLAFAIETE", "CAMPOBOM", "MARICA", "CASCAVEL", "GUARAJUBA", "SAOCAETANO",
		"SAOLEOPOLDO", "BAGRE", "FORTIM", "TAMANDARE", "COLINAS", "SOROCABA", "TIMOTEO",
		"IBIPORA", "PINHAIS", "RIOGRANDE", "CACHOEIRAS", "FOZDOIGUACU", "NOVAIGUACU",
		"MONTEVERDE", "GRAMADO", "BENTO", "CANELA", "MONTEALEGRE", "DIAMANTINA",
		"SANTAREM", "SAOMIGUEL", "CAETE", "LAVRAS", "SAPIRANGA", "SAOMATEUS", "ALAGOINHAS",
		"SALINAS", "NOVAODESSA", "IBIUNA", "CRICIUMA", "PATOSDEM", "UBERABA", "PARAGOMINAS",
		"ALTAMIRA", "BARCARENA", "ICAPUI", "RIOBRANCO", "SENA", "ASSIS", "CACERES",
		"MIRANDAPOLIS", "PALHOCA", "SANTAHELENA", "TRAMANDAI", "SAOJOAO", "BALSAS",
		"BANDEIRANTES", "BAIXAGRANDE", "BIRIGUI", "CRATO", "CRISTINA", "MARAGOGI",
		"OBIDOS", "PIRATUBA", "CANDIDO", "CANANEIA", "CANASVIEIRAS", "SORRISO",
		"MACEDO", "ALTOALEGRE", "CANINDE", "BELOJARDIM", "BELMONTE", "JAU", "FERNANDOPOLIS",
		"TRESLAGOAS", "PORTONACIONAL", "PRESIDENTEPRUDENTE", "MIRASSOL", "CARAMBEI",
		"ARACATUBA", "MARACANAU", "ICAPUI", "TRINDADE", "SANTOANDRE", "RIOCLARO",
		"CABROBO", "GUAJARA", "ARAPIRACA", "MARACAI", "PACATUBA", "OLINDA", "MURIAE",
		"CASTELO", "CAMETA", "POUSO", "SANTACRUZDOCAPIBARIBE", "BOMDESPACHO", "CAMPINAGRANDE",
		"SANTOS", "PIRIPIRI", "PETROLANDIA", "NOVAANDRADINA", "RIONOVO", "RONDON",
		"TIRADENTES", "TRINDADE", "BONFIM", "SANTANADOLIVRAMENTO", "CANDIDO", "PICOS",
		"GOIANIA", "TREMEMBE", "PALMAS", "ALTAMIRA", "MACAE", "OLINDA", "BARRINHA",
		"SANTANA", "BATATAIS", "INDAIATUBA", "CAMPOS", "NOVAODESSA", "SAOLUIZ",
		"PIUMHI", "ITABIRITO", "ARACOIABA", "PASSOS", "ALEGRETE", "SAOBORJA", "BAURU",
		"BOTUCATU", "CUNHA", "CAPAO", "CATU", "DOMINGOSMARTINS", "GUARATINGUETA",
		"ITAPERUNA", "ITAPOLIS", "MARANGUAPE", "NITEROI", "PARATY", "POCINHOS",
		"RIBEIRINHO", "TEOFILOTONI", "TAPIRA", "XAMBIOA", "JOSE", "CANDIDO", "CONGONHAS",
		"ESTRELA", "EUNAPOLIS", "FRANCA", "GUARACUI", "SOBRAL", "PORTOALEGRE", "MOGI",
		"SANTAHELENA", "SANTANADOACU", "VOTUPORANGA", "BARUERI", "PIUMHI", "PELOTAS",
		"TUBARAO", "CAMPINAPOLIS", "CRICIUMA", "RIOBRANCO", "LUCAS", "ALVORADA", "MOGI",
		"CAMPOBELO", "FARROUPILHA", "GUARACI", "LAJEADO", "MUCURI", "ORLANDIA", "PIAUI",
		"SOBRADINHO", "TRESCORACOES", "TRESCORACOES", "VALINHOS", "TREMEMBE", "VESPASIANO",
		"GUARUJA", "ITAQUI", "BARBACENA", "ATIBAIA", "VALENCA", "VITORINO", "FORMIGA",
		"TAMBAU", "ITAQUI", "TRESMARIAS", "SAOMIGUEL", "JANDAIA", "URUPES", "CRISTAIS",
		"JACAREI", "MOGIMIRIM", "BALSAS", "LIMEIRA", "SANTONIO", "VARRE", "APARECIDA",
		"SANTAMONICA", "GUARAJUBA", "SANTANADORIO", "ALVORADA", "LONDRINA", "ITAPIRUNA",
		"SANTAMARIA", "PORTOFRANCO", "BARRA", "PALHOCA", "CUIABA", "GUARABIRA", "MACEIO",
		"CAICARA", "CARAZINHO", "GRAVATAI", "TAPEJARA", "SAOMATEUS", "BAGRE", "UBERLANDIA",
		"PINHEIRO", "CASCAVEL", "SAOBONIFACIO", "SORRISO", "IPATINGA", "UBERABA",
		"PATROCINIO", "LAVRAS", "NOVORUMO", "VILAVELHA", "CATAGUASES", "FRUTAL", "CANGUARETAMA",
		"MONTESCLAROS", "XIQUEXIQUE", "BOMDESPACHO", "JAGUARIBE", "IMBITUBA", "PENEDO",
		"SANTANA", "SANTONIO", "MANACAPURU", "QUITERIANOPOLIS", "URUCUI", "IMBITUBA",
		"SANTANA", "SANTAREM", "FLORIANOPOLIS", "PONTE", "UBERLANDIA", "SANTAMARIA",
		"RIBEIRAOPRETO", "CABOFRIO", "SAOCAETANO", "NOVAODESSA", "GOIANESIA", "CUIABA",
		"TRESMARIAS", "SANTOANTONIO", "FORMIGA", "GUARULHOS", "MARAU", "VIAMAO",
		"GRAMADO", "SAPIRANGA", "MONTEALEGRE", "ITABAIANA", "NOVAFRIBURGO", "PORTOSANTO",
		"LAMEGO", "GUIMARAES", "FARO", "OBIDOS", "BRAGANCA", "FATIMA", "ANGRADOHEROISMO",
		"VISEU", "COVILHA", "OLHAO", "LOURES", "MIRANDA", "ESPINHO", "BARREIRO",
		"ALVERCA", "MARVAO", "MONCAO", "PINHEL", "SINES", "OURIQUE", "OEIRAS",
		"CASCAIS", "BARCELOS", "ESTORIL", "TORRESVEDRAS", "MAFRA", "NAZARE", "POMBAL",
		"CANICAL", "MACHICO", "PORTIMAO", "FUNCHAL", "CALHETA", "ALCOBACA", "LAGOA",
		"QUARTEIRA", "ARMACAO", "OLHAO", "SILVES", "LOULE", "CASTELOBRANCO", "TAVIRA",
		"LISBOA", "PORTO", "AVEIRO", "LEIRIA", "GUARDA", "SANTAREM", "BEJA", "ELVAS",
		"BALEAL", "SEIXAL", "SESIMBRA", "ALBUFEIRA", "LAGOS", "ALMADA", "ODIVELAS",
		"TOMAR", "SANTANA", "MAIA", "FIGUEIRA", "PRAIADAARRAIA", "SANTACRUZ", "CALDAS",
		"VILANOVA", "ESPINHO", "BRAGANCA", "ANGRADOHEROISMO", "MONCHIQUE", "AMADORA",
		"ALCACER", "CAMACHA", "HORTA", "MADALENA", "PORTOMONIZ", "SANTACRUZ", "AZAMBUJA",
		"LOURES", "VILAREAL", "COIMBRA", "MONTEGORDO", "VILANOVADEMILFONTES", "CALDASDACAVARINHA",
		"CASTELOVIDIGUEIRA", "ESTREMOZ", "FERREIRA", "VILAFLOR", "REDONDO", "BORBA",
		"ESTARREJA", "GONDOMAR", "PACOSFERREIRA", "SANTAMARTA", "TROFA", "VALONGO",
		"ESPINHO", "MARGARIDA", "MANTEIGAS", "CAMARADELOBOS",
	},
}

var debug bool = false // Set to true to enable debug logging

// Generate an alias in the format LETTERS.LETTERS.NUMBER
func GenerateAlias(language string) string {
	// Regular expression to validate only letters ABCDEFGHIJKLMNOPQRSTUVWXYZ
	validRegex := regexp.MustCompile(`^[ABCDEFGHIJKLMNOPQRSTUVWXYZ]+$`)

	// Initialize error counters
	duplicateCount := 0
	invalidCount := 0

	// Validate language input and default to "es" if invalid
	if language != "es" && language != "en" && language != "pt" {
		if debug {
			log.Printf("Invalid language '%s'. Defaulting to 'es'.", language)
		}
		language = "es"
	}

	// Filter valid words and remove duplicates for the selected language only
	validWords := make(map[string]struct{}) // Use struct{} for unique sets
	for _, word := range words[language] {
		if validRegex.MatchString(word) {
			// Add only if the word is not already in the set
			if _, exists := validWords[word]; !exists {
				validWords[word] = struct{}{}
			} else if debug {
				log.Printf("Duplicate word removed in '%s': %s\n", language, word)
				duplicateCount++
			}
		} else if debug {
			log.Printf("Invalid word found in '%s': %s\n", language, word)
			invalidCount++
		}
	}

	// If the language has no valid words, default to "es"
	if len(validWords) == 0 && language != "es" {
		if debug {
			log.Printf("No valid words in '%s'. Defaulting to 'es'", language)
		}
		language = "es"
		// Re-run validation for the default language "es"
		validWords = make(map[string]struct{})
		for _, word := range words["es"] {
			if validRegex.MatchString(word) {
				validWords[word] = struct{}{}
			} else if debug {
				log.Printf("Invalid word found in 'es': %s\n", word)
				invalidCount++
			}
		}
	}

	// Print error counts if debug mode is enabled
	if debug {
		fmt.Print("\n")
		log.Printf("Total duplicate words removed: %d\n", duplicateCount)
		log.Printf("Total invalid words found: %d\n", invalidCount)
		log.Printf("Total errors (duplicates + invalids): %d\n", duplicateCount+invalidCount)
	}

	// Convert the set of valid words to a list to select randomly
	uniqueWords := make([]string, 0, len(validWords))
	for word := range validWords {
		uniqueWords = append(uniqueWords, word)
	}

	// Create a random number generator with a specific source
	r := rand.New(rand.NewSource(time.Now().UnixNano()))

	// Select two random words from the selected language
	part1 := uniqueWords[r.Intn(len(uniqueWords))]
	part2 := uniqueWords[r.Intn(len(uniqueWords))]

	// Generate a random number between 100 and 999
	number := r.Intn(900) + 100

	// Format the alias in the desired format
	alias := fmt.Sprintf("%s.%s.%d", part1, part2, number)
	if debug {
		log.Printf("Generated alias: %s\n", alias)
	}
	return alias
}

func main() {
	// Set the default language to "es"
	language := "es"
	if len(os.Args) > 1 {
		// If a language argument is provided, use it
		language = os.Args[1]
	}

	for i := 0; i < 10; i++ {
		alias := GenerateAlias(language)
		fmt.Println("\nGenerated alias:", alias)
	}
}
